[trading]
initial_capital = 100.0
target_daily_return = 0.25
max_positions = 10
default_position_size = 10.0
commission_rate = 0.001
slippage_tolerance = 0.0005

[trading.trading_hours]
market_open = "09:30:00"
market_close = "16:00:00"
timezone = "America/New_York"
trading_days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]

[risk]
max_daily_loss = 2.0
max_position_size = 20.0
var_confidence_level = 0.95
max_portfolio_heat = 0.8
circuit_breaker_threshold = 0.05
emergency_stop_loss = 0.10
correlation_limit = 0.7

[agents.master_coordinator]
enabled = true
decision_timeout_ms = 100
consensus_threshold = 0.7
capabilities = ["StrategyGeneration", "RiskOptimization", "EthicalReasoning"]
strategic_planning_interval_hours = 1

[agents.market_intelligence]
enabled = true
data_sources = ["moomoo"]
update_interval_ms = 100
technical_indicators = ["sma", "ema", "rsi", "macd"]
sentiment_analysis = true
pattern_recognition = true

[agents.risk_management]
enabled = true
monitoring_interval_ms = 50
stress_testing = true
monte_carlo_simulations = 1000
dynamic_hedging = true

[agents.execution_engine]
enabled = true
max_latency_ms = 1
order_routing_optimization = true
slippage_optimization = true
execution_algorithms = ["twap", "vwap"]

[agents.learning_engine]
enabled = true
model_update_interval_hours = 4
online_learning = true
ensemble_models = true
strategy_generation = true

[api.moomoo]
base_url = "http://127.0.0.1:11111"
api_key = "demo_12345"
secret_key = "demo_secret_67890"
paper_trading = true
timeout_ms = 5000
retry_attempts = 3

[api.rate_limits]
requests_per_second = 100
burst_limit = 200
backoff_strategy = "exponential"

[[api.data_providers]]
name = "moomoo"
url = "http://127.0.0.1:11111"
enabled = true
priority = 1

[monitoring]
metrics_enabled = true
prometheus_port = 9090
log_level = "info"
performance_tracking = true

[monitoring.alerts]
enabled = true
email_notifications = false
slack_webhook = ""
critical_loss_threshold = 5.0
performance_degradation_threshold = 0.5

[[strategies]]
name = "momentum_scalping"
enabled = true
risk_limit = 1.0
max_position_size = 10.0
parameters = {}

[[strategies]]
name = "mean_reversion"
enabled = true
risk_limit = 1.0
max_position_size = 10.0
parameters = {}
